- name: Download selenium on 'master' if we don't have it
  connection: local
  sudo: False
  get_url: url={{download_url}}  dest={{cur_dir}}/{{jar_file}} force=no

- name: Verify integrity of downloaded file
  connection: local
  sudo: False
  command: unzip -qt {{cur_dir}}/{{jar_file}}

# Setup/install tasks.
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: debian.yml
  when: ansible_os_family == 'Windows'
