---
- name: Download selenium on 'master' if we don't have it
  connection: local
  sudo: False
  environment: proxy_env
  get_url: url={{download_url}}  dest={{cur_dir}}/{{jar_file}} force=no

- name: Verify integrity of downloaded file
  connection: local
  sudo: False
  command: unzip -qt {{cur_dir}}/{{jar_file}}

- name: Ensure Selenium group exists
  group: name="{{ selenium_group }}" state=present
  sudo: true

- name: Ensure Selenium user exists
  user: name="{{ selenium_user }}" group="{{ selenium_group }}" shell="/bin/bash" state=present
  sudo: true

- name: Copy selenium into place
  sudo: True
  copy: src={{jar_file}}  dest={{ selenium_dir }}/selenium-server.jar owner=root group=root mode=644

- name: Install Config
  sudo: True
  template: src=defaults.j2 dest=/etc/default/se_{{sel_role}} owner=root group=root mode=644
  tags: ['config']

- name: Install service file
  sudo: True
  template: src=redhat_init.j2 dest=/etc/init.d/se_{{sel_role}} owner=root group=root mode=755
  tags: ['config']

- name: Enable service
  sudo: True
  service: name=se_node enabled=yes state=started
  when: sel_role == 'node'

- name: Enable service
  sudo: True
  service: name=se_hub enabled=yes state=started
  when: sel_role == 'hub'

- name: Install browser
  sudo: True
  yum: name={{item}}
  with_items:
    - xorg-x11-server-Xvfb
    - firefox
  when:  sel_role != 'hub'
